### ISSUE TITLE
Módulo 1.1 Tarea

### ISSUE THREAD

**Issue by IngRoberth** [SistemasTecTlaxiaco/roberto#1]
Teniendo en cuenta lo que has aprendido sobre Git, ¿por qué querrías usar Git en tu salón de clases?

**Comment by IngRoberth** [comment]
Personalmente pienso que seria una herramienta tecnológica potente para desarrollar trabajos colaborativos, que a futuro convertirán a los jóvenes en grandes lideres de proyectos tecnológicos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
